### ISSUE TITLE
https://www.bountysource.com

### ISSUE THREAD

**Issue by necrose99** [bolorundurowb/Open-Exam-Suite#1]
if this will also support mono , then will run on macos , Linux etc. 

http://www.monodevelop.com/archived/download/mono-for-android/

as well if you want help , I'd put 5 on it. its about all I got , just the VCE files are a Tyrannically priced.

65 for year expensive but not a gouge. but mo'ly or having to beg my certification school for home use irritating. 
http://sourceforge.net/projects/mnemosyne-proj/?source=directory would have some elements you could abuse. 

As well open Office ms word XML   Macros Style sheets  ----> XSL   OSEXML is a future posible. .... 

anyhow collect donations post bounty for a import/export library.

**Comment by necrose99** [comment]
[libcryptvce.c.txt](https://github.com/bolorundurowb/Open-Exam-Suite/files/57611/libcryptvce.c.txt)

https://my.pcloud.com/publink/show?code=XZF4IzZtvbQ8uuobBSkORClgyCJshHzVGEV DLL

https://my.pcloud.com/publink/show?code=XZz4IzZDKUCg7B9PVyM3Hs2GChJ6BOxHtjX  APP Launcher

https://derevenets.com/ https://retdec.com/decompilation-run/  anyhow these are the out.

**Comment by bolorundurowb** [comment]
Thank you very much. This should help a lot

**Comment by necrose99** [comment]
no biggy , I've got CISSP etc to grind , and other certs , I can see 120-200 for the year but 50 a month is not realistic for students.  and it forces RDESKTOP to my certification school. and for the schools they bilk'em for thousands per month. 

anyhow its sql light  encrypted code. have fun with that one...
