### ISSUE TITLE
VCE exams to the OEF

### ISSUE THREAD

**Issue by cherazo** [bolorundurowb/Open-Exam-Suite#13]
Hi Team,

Is there any option to re-add the vce converter to oef?? it would be a great feature to start using the Open-Exa-Suite instead of the known vce player.

Thanks for the effort and replies.

**Comment by bolorundurowb** [comment]
Hello @cherazo ,
It was part of the original scheme to convert VCE files to OEF but as I faced some difficulty with that, I decided to reprioritize, by implementing the core features of VCE Exam Suite in Open Exam Suite so people can easily switch. Once all the features are replicated, I'll look into porting the exams once more. Watch out for version 3.1 coming soon. Any other concerns?

**Comment by cherazo** [comment]
Not, at this point i'm good testing the current version.

Thank you so much for the effort!

**Comment by carvajalluis** [comment]
has this had any progress ?

**Comment by bolorundurowb** [comment]
@luigilabel Currently, no. But if you know anyway I could, then please share.

**Comment by walataza** [comment]
@bolorundurowb  ..Trust this message meets you well. May i know if there is a way to convert .vce files to .oeff ... Or is there a way to open .vce files in your open source exam simulator?
Thnaks in advance

**Comment by andjimrio** [comment]
RT to @walataza 

I am trying to search a alternative to VCE. My problem is that I have VCE exams that I cannot read. Any ideas?

**Comment by walataza** [comment]
Hello Andres,
there is a windows vce client which you can search via the windows store.
Alternatively you have to use android, if you will prefer to use your pc
still, try using Remix Os on pc, its an android flavored OS. If you have
any more requests, do let me know

warm regards

**Comment by Jonesnetwork** [comment]
Looking for the VCE to OEF converter? (If there is one?)

**Comment by wtf911** [comment]
No update on this issue?

**Comment by bolorundurowb** [comment]
There is currently no update on this issue

**Comment by ghost** [comment]
I figured out how to parse some versions of the vce format, if it's still relevant...

**Comment by seichodev** [comment]
> I figured out how to parse some versions of the vce format, if it's still relevant...

Ghost, I am begging you with tears in my eyes please tell me how. I need to be able to play VCE files offline for free or at least convert them to OEF....
