### ISSUE TITLE
Feature Request:  JSON & XML Import

### ISSUE THREAD

**Issue by dmidlo** [bolorundurowb/Open-Exam-Suite#17]
Would like the ability create tests using a single text file in creator

**Comment by bolorundurowb** [comment]
Good day @querentCode I am not quite sure what you mean by `using a single text file`, do you mean that you want to be able to import the questions from  a text file?

**Comment by dmidlo** [comment]
No....  consider it 'filler language'.  Would simply like the ability to import a formatted XML or JSON file into the test creator.

**Comment by bolorundurowb** [comment]
Alright, @querentCode so for version 3.2, `JSON Imports` would be added.

**Comment by bolorundurowb** [comment]
@querentCode You can now Open a JSON or XML file and save it as an OEF
