### ISSUE TITLE
New & Inexperienced Developer, Love the project. Where can I help? 

### ISSUE THREAD

**Issue by dmidlo** [bolorundurowb/Open-Exam-Suite#18]

**Comment by bolorundurowb** [comment]
Well @querentCode , thanks for the offer. This project is implemented in C# I am not sure how much experience you have with the language.
No matter what, I am very sure there is a host of ways you can help. The aim of this project is to implement full feature parity with VCE Exam Suite. 
As I prepare more features for version 3.2, I'll be sure to include you

**Comment by bolorundurowb** [comment]
Hey @querentCode I think I have found a way for you to help out on the project if you're still interested. I believe it would be great if the app logged errors and events instead of breaking. I have added it the the `version 3.1` milestone. Are you interested?

**Comment by bolorundurowb** [comment]
@querentCode Doesnt seem like you aren't interested anymore. So I am closing this

**Comment by StudiousDesign** [comment]
@bolorundurowb I'm interested in helping out on this project.
