### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by teacherguy** [bolorundurowb/Open-Exam-Suite#25]
In 3.1, I have an issue with the app crashing when I press the back button to revisit a previous question.

**Comment by bolorundurowb** [comment]
Hello @teacherguy Thanks for pointing that out. I will try to replicate it and work on a fix

**Comment by JonnyS1** [comment]
Hi Bolorundurowb,

Just confirming this is occurring for me too. A test file you can use where this is occurring can be found here:

[Clicky linky](https://1drv.ms/u/s!AsuUGOUASvpoa57LCIKEuFHmXtU)

**Comment by bolorundurowb** [comment]
Hello @JonnyS1 just to confirm, this error occurs in the Simulator right?

**Update**
I have just confirmed this bug. I will create a branch for the fix and create a PR. I'll keep you posted

**Comment by bolorundurowb** [comment]
You can get the update from the releases page or SourceForge @JonnyS1
