### ISSUE TITLE
Potential file size limit?

### ISSUE THREAD

**Issue by JonnyS1** [bolorundurowb/Open-Exam-Suite#26]
Hi Bolorundurowb,

This program is fantastic, great effort and thanks for all your work on it. I have come across an issue with a file I've been creating that may be too big for the program?

My original 25Q file found [here ](https://1drv.ms/u/s!AsuUGOUASvpoa57LCIKEuFHmXtU) loads in the Creator and Simulator no problem and is about 3.5MB. 

I have proceeded to expand this file up to around 14.5MB (link [here](https://1drv.ms/u/s!Anc4GackMlB0gdFaHl4O6PLP7n6QWg)) and have now encountered an issue where the Simulator gives me this message:

![image](https://cloud.githubusercontent.com/assets/25094929/21918552/5c4bed52-d98d-11e6-9dbd-1b9d3cd99566.png)

Trying to load it in the creator gives me this error message: 

![image](https://cloud.githubusercontent.com/assets/25094929/21918527/26abbb1e-d98d-11e6-82c0-832d9dae3a53.png)

With the following debug output:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Creator.UI.Open()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1086.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Creator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Open%20Exam%20Suite/Creator.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1084.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Shared
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Open%20Exam%20Suite/Shared.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

I have uninstalled/re-installed the program but no joy. Any help with this would be much appreciated as it took me 2-3 days to make the larger file and I'd love to continue with it!

Thanks,
Jonny

**Comment by bolorundurowb** [comment]
Hello @JonnyS1 I will look into this and try and replicate the issue and work on a solution

**Comment by JonnyS1** [comment]
Thanks Bolorundurowb, much appreciated. I had an incorrect link for the large file share which is experiencing the issue, the new link is here:

[Link](https://1drv.ms/u/s!AsuUGOUASvpobJd_fpqcF-Pvir0)

Thanks,
Jonny

**Comment by bolorundurowb** [comment]
Hello @JonnyS1 I have looked into this issue and it seems like your file is corrupted. there is no file size limit. I will add some checks to display an appropriate message and not crahs.

**Comment by bolorundurowb** [comment]
You can get the update from the releases page or SourceForge @JonnyS1
