### ISSUE TITLE
open quiz tools

### ISSUE THREAD

**Issue by necrose99** [bolorundurowb/Open-Exam-Suite#3]
https://sourceforge.net/projects/testmaker/
https://github.com/softon/ProQuiz

also seen a free one with moodle xml export. import..

**Comment by bolorundurowb** [comment]
The one with the XML export is the best candidate

**Comment by necrose99** [comment]
http://schoolofdata.org/2013/08/16/scraping-pdfs-with-python-and-the-scraperwiki-module/
http://www.quizfaber.com/index.php/en/download-eng , exports to [moodle ](https://moodle.org/) xml 
, though freeware not sure the author will have it as open-source.  
http://sourceforge.net/projects/moodletoolkit/files/  word to moodle quiz xml.  however is. 
gives web based option to export quizzes to moodle CMS. 

http://sketchman-studio.com/profexam/ or vce palyer can take PDF files with Quiz data pics etc before converting them into .exam or vce.... files

https://bitbucket.org/petermr/pdf2svg/wiki/Home
https://pypi.python.org/pypi/svglue
https://github.com/micahpearlman/MonkSVG 
https://sourceforge.net/projects/itextsharp/
http://stackoverflow.com/questions/10689382/extract-image-from-a-particular-page-in-pdf
http://p-s.co.nz/wordpress/pdf-to-png-using-pythonmagick/

XML+HTML 5 should be simple enough , http://www.www9.org/w9cdrom/154/154.html 
ie custom XML html5 is xml spec , and html people get it.  as well any XSL converters are doable. 
including html to markdown etc. easy way to be as open as possible. 
https://en.wikipedia.org/wiki/HTML5#XHTML5_.28XML-serialized_HTML5.29
http://www.c-sharpcorner.com/UploadFile/88d8c0/read-xml-document-using-vb-script-and-html5/
https://github.com/rmcn/PythonEmbrace
larger scale programing i'm not skilled at. however bash etc basic scripts are enough. 

if I had bill gates money i get the 30,000 foot view of programing , just the 3 foot view and banging code out of my dyslexic skull sometimes leads to a train....wreck sometimes it leads to perfection. 

xhtml5 tokenized to binary powerful , svg tokenized to save space, pdf/xml is known spec. 
also makes for easy html5 export of quizzes for web-based cbt also , less of a hell in export , 
and if you want pretty quizzes and custom my inc logos etc,  details etc can pull in web pages or downloads... http://www.cisspexampractice.com   or score pages , ie rebuild a quiz for offline use locally. 
http://www.cisspexampractice.com wasnt too bad but workintexas.com (tx.gov) paid for it should i got for CISA etc can get 'spensive.... 
but as a **Security Engineer** I just need scripts , crude but effective to automate testing or app scans for holes/faults... 
all the Certs we have to take anything that can shave off a few bucks...  I can appreciate efforts. 
a few possible ways of skinning hides but not the only way. 

my curse is i can see full apps how to architect them possibly...... but suck at actually doing them...

**Comment by necrose99** [comment]
https://vcetrainer.com opens vce or professor exam files, can convert un-encrypted to pdf.
also prof exam files to pdf.  (unfortunately  the how is not known.) 

PDF into exam , is how my last training provider built thier simulation exams on VCE-player (or also profexam) 

 http://www.examcollection.com/comptia_exams.html 

http://exam-files.com/exams/ http://sketchman-studio.com/profexam/ 
(not free but considerably friendly to wallet than some of VCE players prior terms. ) 
http://exam-files.com/exams/ can get a few here. 

anyhow https://vce2pdf.com/ but $ . 
**some means of reversing the how would be good.** 
these are known banks of tests for either player , most convert to/from PDF , some are crypto locked. 

both tools use sqlite  if that helps someone interested  in reversing vce/exame files. 
sure you can print to pdf however a means of doing it programmatically a plus. 
http://www.infotechnopedia.com/vcetopdf/  , one that claims to work , .net etc however you have to spam your life away with surveys and offers just to crack at it, let alone reverse its .net code. 
may be of use to someone good at reversing engineering file-formats  

http://blog.andreiclinciu.net/?p=237
http://code.activestate.com/recipes/579027-publish-sqlite-data-to-pdf-using-named-tuples/
https://github.com/pythonnet/pythonnet
http://techawakening.org/convert-vce-files-to-pdf/167/
https://github.com/praeclarum/sqlite-net

I/O /Conversion  of PDF , Exam and VCE files , might be good to have.
