### ISSUE TITLE
Feature Request - VCE Import

### ISSUE THREAD

**Issue by the-mentor** [bolorundurowb/Open-Exam-Suite#32]
in order to fully switch from other exam simulators we will need an easy way to convert existing VCE exams to Open-Exam.

thank you very much.

**Comment by bolorundurowb** [comment]
Hello @the-mentor for now I dont see how I can implement VCE imports as there is no avccessible library for me to read the vce binaries so I would be closing this for now. Please feel free to reopen it if something new comes up
