### ISSUE TITLE
Support for .vce files

### ISSUE THREAD

**Issue by singhvikas235** [bolorundurowb/Open-Exam-Suite#34]
Hi,

Thank you for the much needed application. Much appreciated.

 It's sad to see that there's no support for .vce files or converter from .vce to .opef files and thus will request you to make it support .vce files. Most of the IT exams are in .vce format and thus its a much needed feature.

Thanks in advance.

Vikas

**Comment by bolorundurowb** [comment]
@singhvikas235 I know that vce support is required and its top on my list of priorities but there are some huge issues to be resolved before that can be done

**Comment by bolorundurowb** [comment]
@singhvikas235 I would be closing this for now since there is no way for me to convert the VCE files now. Please feel free to reopen it if any new thing comes up
