### ISSUE TITLE
Multiline field for Answer Explanation

### ISSUE THREAD

**Issue by jmkstack** [bolorundurowb/Open-Exam-Suite#35]
The answer explanation field is currently only a single line input field.
This is not sufficient for giving more detailed explanations. Worse, even it you paste a long explantion into this line, the simulator cuts off the line.
Is it possible to make the explantion field a multi line field like the Question Text?

**Comment by bolorundurowb** [comment]
@jmkstack I will add it to the next release. Thank for raising this isse
