### ISSUE TITLE
Convert OEF to VCE

### ISSUE THREAD

**Issue by rdinnik** [bolorundurowb/Open-Exam-Suite#43]
It would be grate also conver OEF to VCE since mobile app for ios and andriod for vce still alive and mature and provide good functionality for free. I'm currently looking for free vce designer(creator) or ablitiy to conver any other format to VCE.

**Comment by bolorundurowb** [comment]
@rdinnik that is a great idea but the same limitation that prevents me converting VCE to OEF stops me converting the other way
