### ISSUE TITLE
Multiple choice answers

### ISSUE THREAD

**Issue by iHateThisGameSo** [bolorundurowb/Open-Exam-Suite#8]
Please allow some answers to be more than one choice. Only marks a point if all answers are correct (or make this behavior configurable). Right now when building an exam I can select multiple choices on a question, but after saving and editing it again, it only shows the first selected answer during creation as correct (filled radio button)

**Comment by bolorundurowb** [comment]
@ppucci Thanks for the feedback. Currently the app only supports a single answer per question. In the next update, multiple choice would be implemented.

**Comment by bolorundurowb** [comment]
@ppucci Work has begun on this feature and you can check the `version3.1` branch to see whats being done.
