### ISSUE TITLE
Import from PDF

### ISSUE THREAD

**Issue by AltarBeastiful** [bolorundurowb/Open-Exam-Suite#98]
There's already a lot of exam training in PDF format. Also VCE files can easily be converted to PDF.
Ability to import those would greatly increase the number of training test available.

You can easily do on import from PDF by converting to text and using regex for questions and answers part.

**Comment by Wajinn** [comment]
> VCE files can...
You are requesting the author engage in illegal activities that can get him in major trouble.  Stealing of copyrighted material, creating tools to facilitate copyright infringement, among the least of it.  Should not be asking for others to get in such trouble, where they can go to jail.
